package studio.seer.lineage.resource;

import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import org.eclipse.microprofile.graphql.*;
import studio.seer.lineage.model.*;
import studio.seer.lineage.security.SeerIdentity;
import studio.seer.lineage.service.*;

import java.util.List;

/**
 * GraphQL API for SEER LOOM — three view levels + search.
 *
 * All queries are intent-based: the client never sends raw Cypher/SQL.
 * Role enforcement is in SeerIdentity (via X-Seer-Role from rbac-proxy).
 *
 * Schema auto-generated by SmallRye GraphQL from method signatures.
 * Browse at http://localhost:8080/graphql-ui in dev mode.
 */
@GraphQLApi
public class LineageResource {

    @Inject SeerIdentity  identity;
    @Inject OverviewService overviewService;
    @Inject ExploreService  exploreService;
    @Inject LineageService  lineageService;
    @Inject SearchService   searchService;

    // ── L1: Overview ──────────────────────────────────────────────────────────

    @Query("overview")
    @Description("L1 — aggregated list of schemas with counts. Role: viewer+")
    public Uni<List<SchemaNode>> overview() {
        return overviewService.overview();
    }

    // ── L2: Explore ───────────────────────────────────────────────────────────

    @Query("explore")
    @Description("L2 — tables and routines within a schema or package scope. Role: viewer+")
    public Uni<ExploreResult> explore(
        @Name("scope")
        @Description("'schema-<name>', 'pkg-<name>', or a raw @rid")
        String scope
    ) {
        return exploreService.explore(scope);
    }

    // ── L2+: Statement column enrichment ─────────────────────────────────────

    @Query("stmtColumns")
    @Description("Bulk HAS_OUTPUT_COL + HAS_AFFECTED_COL for a list of statement @rids. Role: viewer+")
    public Uni<ExploreResult> stmtColumns(
        @Name("ids")
        @Description("List of statement @rids returned by explore")
        List<String> ids
    ) {
        return exploreService.exploreStmtColumns(ids);
    }

    // ── L3: Column lineage ────────────────────────────────────────────────────

    @Query("lineage")
    @Description("L3 — full bidirectional column lineage for a node. Role: viewer+")
    public Uni<ExploreResult> lineage(
        @Name("nodeId")
        @Description("@rid of a DaliTable or DaliColumn vertex")
        String nodeId
    ) {
        return lineageService.lineage(nodeId);
    }

    @Query("upstream")
    @Description("L3 — upstream lineage only (what feeds into this node). Role: viewer+")
    public Uni<ExploreResult> upstream(@Name("nodeId") String nodeId) {
        return lineageService.upstream(nodeId);
    }

    @Query("downstream")
    @Description("L3 — downstream impact (what this node affects). Role: viewer+")
    public Uni<ExploreResult> downstream(@Name("nodeId") String nodeId) {
        return lineageService.downstream(nodeId);
    }

    // ── Search ────────────────────────────────────────────────────────────────

    @Query("search")
    @Description("Full-text search across tables, columns, routines. Role: viewer+")
    public Uni<List<SearchResult>> search(
        @Name("query") String query,
        @Name("limit") @DefaultValue("20") int limit
    ) {
        return searchService.search(query, Math.min(limit, 100));
    }

    // ── Meta ──────────────────────────────────────────────────────────────────

    @Query("me")
    @Description("Current identity as seen by lineage-api")
    public String me() {
        return identity.username() + " (" + identity.role() + ")";
    }
}
